### ISSUE TITLE
Script doesn't detect invalid usernames

### ISSUE THREAD

**Issue by johnjurkov** [initstring/linkedin2username#10]
For example, single letters where the script could not retrieve the full name of the user.

**Comment by initstring** [comment]
Thanks mate, this might be a regression... will look into it ASAP.

**Comment by initstring** [comment]
This was a great find, thanks. Turns out that when dealing with hyphens and such, one of the regex lines was introducing a new whitespace and messing things up later on in the script.

I believe this is now [fixed](https://github.com/initstring/linkedin2username/commit/352198c12c5349c90e566eb538b8095ebbe13534). I am still allowing usernames with a single letter for last name and first name (as long as both exist), which is unlikely to be valid but still possible and technically fits the specs of the output files.

Thanks again!!!
