### ISSUE TITLE
Some account notification

### ISSUE THREAD

**Issue by MosaicEffect** [initstring/linkedin2username#32]
Hi, 

When I run the tool i get the following message:

[*] Using version 0.21, which is the latest on GitHub.

[!] LinkedIn has some account notification for you to check. Please log in first via the web and clear that.

I have logged into via the web and there are no messages, notifications, new connections or other obvious alerts?

**Comment by Angelozinna96** [comment]
Same issue!

**Comment by initstring** [comment]
This happens when the login redirects to a URL with `manage_account` inside. I just tried to reproduce but cannot - the tool works fine for me.

You can try running the tool through a proxy like ZAP or Burp to get more details on what is happening. There is a `--proxy` flag to make that easy.

If you can figure it out, can you please update this issue with the details?

Thanks!

**Comment by initstring** [comment]
No replies, closing issue. Feel free to add more details if you are still having problems.

**Comment by BlackAp3rture** [comment]
@Angelozinna96 LinkedIn is trying to verify email/phone# on login. Logout, clear browser cache, confirm the information when relogging in, and then try again.
